'use strict';-

jest.mock('../../models', () => ({
  Pohon:           { findAll: jest.fn(), update: jest.fn() },
  Penanaman:       { findAll: jest.fn(), findByPk: jest.fn() },
  ProgramDonasi:   {},
  JenisPohon:      {},
  Mitra:           {},
  DetailMonitoring: {
    update:  jest.fn(),
    findOne: jest.fn()
  },
  Monitoring: {
    findByPk: jest.fn(),
    findOne:  jest.fn()
  }
}));

jest.mock('../../services/wilayahService', () => ({
  mapWilayah: jest.fn()
}));

jest.mock('sequelize', () => ({
  Op: { in: Symbol('in') }
}));


const {
  Pohon,
  Penanaman,
  DetailMonitoring,
  Monitoring
} = require('../../models');

const WilayahService =
  require('../../services/wilayahService');

const VerifikasiPohonController =
  require('../../controllers/VerifikasiPohonController');


const buatPohon = (overrides = {}) => {

  const base = {
    id_pohon:          1,
    status_verifikasi: 'menunggu',
    detailMonitoring:  [],
    ...overrides
  };

  return {
    ...base,
    toJSON: () => ({ ...base })
  };

};

const buatDetail = (overrides = {}) => {

  const base = {
    id_monitoring:    1,
    id_pohon:         1,
    status_verifikasi: 'menunggu',
    status:           'hidup',
    foto_monitoring:  '[]',
    monitoring:       { tahap_monitoring: 1 },
    ...overrides
  };

  return {
    ...base,
    toJSON:  () => ({ ...base }),
    update:  jest.fn().mockResolvedValue(true)
  };

};


const buatReqRes = (overrides = {}) => {

  const req = {
    params: {},
    body:   {},
    user:   { id_user: 99 },
    ...overrides
  };

  const res = {
    render:   jest.fn(),
    send:     jest.fn(),
    redirect: jest.fn()
  };

  return { req, res };

};



describe('VerifikasiPohonController', () => {

  beforeEach(() => {
    jest.clearAllMocks();
    jest.spyOn(console, 'log').mockImplementation(() => {});
    jest.spyOn(console, 'error').mockImplementation(() => {});
  });

  describe('_toArray', () => {

    test('mengembalikan array kosong jika value null', () => {
      expect(
        VerifikasiPohonController._toArray(null)
      ).toEqual([]);
    });

    test('mengembalikan array kosong jika value undefined', () => {
      expect(
        VerifikasiPohonController._toArray(undefined)
      ).toEqual([]);
    });

    test('membungkus string tunggal menjadi array', () => {
      expect(
        VerifikasiPohonController._toArray('abc')
      ).toEqual(['abc']);
    });

    test('mengembalikan array asli jika sudah array', () => {
      expect(
        VerifikasiPohonController._toArray(['a', 'b'])
      ).toEqual(['a', 'b']);
    });

    test('mengembalikan array kosong jika value string kosong', () => {
      expect(
        VerifikasiPohonController._toArray('')
      ).toEqual([]);
    });

  });


  describe('_isAutoGenerated', () => {

    test('true jika status mati dan foto kosong []', () => {
      const detail = buatDetail({
        status:          'mati',
        foto_monitoring: '[]'
      });
      expect(
        VerifikasiPohonController._isAutoGenerated(detail)
      ).toBe(true);
    });

    test('true jika status mati dan foto_monitoring null', () => {
      const detail = buatDetail({
        status:          'mati',
        foto_monitoring: null
      });
      expect(
        VerifikasiPohonController._isAutoGenerated(detail)
      ).toBe(true);
    });

    test('false jika status mati tapi ada foto', () => {
      const detail = buatDetail({
        status:          'mati',
        foto_monitoring: '["foto1.jpg"]'
      });
      expect(
        VerifikasiPohonController._isAutoGenerated(detail)
      ).toBe(false);
    });

    test('false jika status bukan mati', () => {
      const detail = buatDetail({
        status:          'hidup',
        foto_monitoring: '[]'
      });
      expect(
        VerifikasiPohonController._isAutoGenerated(detail)
      ).toBe(false);
    });

    test('false jika foto_monitoring adalah JSON tidak valid', () => {
      // JSON invalid → fotoArr = [] → bergantung pada status
      const detail = buatDetail({
        status:          'hidup',
        foto_monitoring: 'INVALID_JSON'
      });
      expect(
        VerifikasiPohonController._isAutoGenerated(detail)
      ).toBe(false);
    });

    test('true jika status mati dan foto_monitoring JSON invalid (dianggap kosong)', () => {
      const detail = buatDetail({
        status:          'mati',
        foto_monitoring: 'BUKAN_JSON'
      });
      // Karena JSON.parse gagal, fotoArr tetap [] → dianggap auto-generated
      expect(
        VerifikasiPohonController._isAutoGenerated(detail)
      ).toBe(true);
    });

  });


  // ===========================================================
  // HELPER: _hitungOverallStatus
  // ===========================================================
  describe('_hitungOverallStatus', () => {

    test('pohon menunggu tanpa monitoring → status Data Penanaman', () => {
      const pohon = buatPohon({
        status_verifikasi: 'menunggu',
        detailMonitoring:  []
      });
      expect(
        VerifikasiPohonController._hitungOverallStatus(pohon)
      ).toEqual({
        overallStatus: 'menunggu',
        overallTahap:  'Data Penanaman'
      });
    });

    test('pohon revisi tanpa monitoring → status Data Penanaman', () => {
      const pohon = buatPohon({
        status_verifikasi: 'revisi',
        detailMonitoring:  []
      });
      expect(
        VerifikasiPohonController._hitungOverallStatus(pohon)
      ).toEqual({
        overallStatus: 'revisi',
        overallTahap:  'Data Penanaman'
      });
    });

    test('pohon disetujui tanpa monitoring → status Data Penanaman', () => {
      const pohon = buatPohon({
        status_verifikasi: 'disetujui',
        detailMonitoring:  []
      });
      expect(
        VerifikasiPohonController._hitungOverallStatus(pohon)
      ).toEqual({
        overallStatus: 'disetujui',
        overallTahap:  'Data Penanaman'
      });
    });

    test('ada monitoring revisi → overallStatus revisi, tahap dari monitoring', () => {
      const pohon = buatPohon({
        status_verifikasi: 'disetujui',
        detailMonitoring: [
          {
            status_verifikasi: 'revisi',
            monitoring: { tahap_monitoring: 2 }
          }
        ]
      });
      expect(
        VerifikasiPohonController._hitungOverallStatus(pohon)
      ).toEqual({
        overallStatus: 'revisi',
        overallTahap:  'Monitoring 2'
      });
    });

    test('ada monitoring menunggu → overallStatus menunggu, tahap dari monitoring', () => {
      const pohon = buatPohon({
        status_verifikasi: 'disetujui',
        detailMonitoring: [
          {
            status_verifikasi: 'menunggu',
            monitoring: { tahap_monitoring: 1 }
          }
        ]
      });
      expect(
        VerifikasiPohonController._hitungOverallStatus(pohon)
      ).toEqual({
        overallStatus: 'menunggu',
        overallTahap:  'Monitoring 1'
      });
    });

    test('revisi lebih diprioritaskan dari menunggu', () => {
      // Jika ada kedua-duanya, revisi harus menang
      const pohon = buatPohon({
        status_verifikasi: 'disetujui',
        detailMonitoring: [
          {
            status_verifikasi: 'menunggu',
            monitoring: { tahap_monitoring: 1 }
          },
          {
            status_verifikasi: 'revisi',
            monitoring: { tahap_monitoring: 2 }
          }
        ]
      });
      const result =
        VerifikasiPohonController._hitungOverallStatus(pohon);
      expect(result.overallStatus).toBe('revisi');
    });

    test('pohon disetujui dengan monitoring disetujui → tahap dari monitoring tertinggi', () => {
      const pohon = buatPohon({
        status_verifikasi: 'disetujui',
        detailMonitoring: [
          {
            status_verifikasi: 'disetujui',
            monitoring: { tahap_monitoring: 3 }
          },
          {
            status_verifikasi: 'disetujui',
            monitoring: { tahap_monitoring: 1 }
          }
        ]
      });
      const result =
        VerifikasiPohonController._hitungOverallStatus(pohon);
      expect(result.overallStatus).toBe('disetujui');
      // monSorted descending → tahap 3 di index 0 → Monitoring 3
      expect(result.overallTahap).toBe('Monitoring 3');
    });

    test('pohon disetujui dengan monitoring ada tapi belum ada yang disetujui → tahap Data Penanaman', () => {
      const pohon = buatPohon({
        status_verifikasi: 'disetujui',
        detailMonitoring: [
          // Semua monitoring belum disetujui tapi bukan revisi/menunggu
          // Edge case: status_verifikasi kosong / null
          {
            status_verifikasi: null,
            monitoring: { tahap_monitoring: 1 }
          }
        ]
      });
      const result =
        VerifikasiPohonController._hitungOverallStatus(pohon);
      expect(result.overallStatus).toBe('disetujui');
      expect(result.overallTahap).toBe('Data Penanaman');
    });

    test('detailMonitoring tidak ada (undefined) → dianggap array kosong', () => {
      const pohon = buatPohon({
        status_verifikasi: 'menunggu',
        detailMonitoring:  undefined
      });
      expect(() =>
        VerifikasiPohonController._hitungOverallStatus(pohon)
      ).not.toThrow();
    });

  });


  // ===========================================================
  // HELPER: _agregasiStatusPohon
  // ===========================================================
  describe('_agregasiStatusPohon', () => {

    test('menghitung totalVerifikasi dengan benar', () => {
      const pohonList = [
        buatPohon({ status_verifikasi: 'disetujui', detailMonitoring: [] }),
        buatPohon({ status_verifikasi: 'disetujui', detailMonitoring: [] }),
        buatPohon({ status_verifikasi: 'menunggu',  detailMonitoring: [] })
      ];

      const { totalVerifikasi, totalMenunggu } =
        VerifikasiPohonController._agregasiStatusPohon(pohonList);

      expect(totalVerifikasi).toBe(2);
      expect(totalMenunggu).toBe(1);
    });

    test('menghitung totalMenunggu termasuk pohon revisi', () => {
      const pohonList = [
        buatPohon({ status_verifikasi: 'revisi',   detailMonitoring: [] }),
        buatPohon({ status_verifikasi: 'menunggu', detailMonitoring: [] }),
        buatPohon({ status_verifikasi: 'disetujui',detailMonitoring: [] })
      ];

      const { totalMenunggu } =
        VerifikasiPohonController._agregasiStatusPohon(pohonList);

      // revisi + menunggu = 2
      expect(totalMenunggu).toBe(2);
    });

    test('array kosong → semua total nol', () => {
      const { totalVerifikasi, totalMenunggu } =
        VerifikasiPohonController._agregasiStatusPohon([]);

      expect(totalVerifikasi).toBe(0);
      expect(totalMenunggu).toBe(0);
    });

    test('pohonDenganStatus memiliki field overallStatus dan overallTahap', () => {
      const pohonList = [
        buatPohon({ status_verifikasi: 'disetujui', detailMonitoring: [] })
      ];

      const { pohonDenganStatus } =
        VerifikasiPohonController._agregasiStatusPohon(pohonList);

      expect(pohonDenganStatus[0]).toHaveProperty('overallStatus');
      expect(pohonDenganStatus[0]).toHaveProperty('overallTahap');
    });

  });


  // ===========================================================
  // HELPER: _kelompokkanMonitoringPerTahap
  // ===========================================================
  describe('_kelompokkanMonitoringPerTahap', () => {

    const buatPohonDenganMonitoring = (detailList) => {
      return {
        id_pohon:         1,
        detailMonitoring: detailList.map(d => ({
          ...d,
          toJSON: () => ({ ...d })
        }))
      };
    };

    test('mengelompokkan detail ke monitoring1, 2, 3 dengan benar', () => {
      const pohonList = [
        buatPohonDenganMonitoring([
          { id: 'a', monitoring: { tahap_monitoring: 1 } },
          { id: 'b', monitoring: { tahap_monitoring: 2 } },
          { id: 'c', monitoring: { tahap_monitoring: 3 } }
        ])
      ];

      const { monitoring1, monitoring2, monitoring3 } =
        VerifikasiPohonController
          ._kelompokkanMonitoringPerTahap(pohonList);

      expect(monitoring1).toHaveLength(1);
      expect(monitoring2).toHaveLength(1);
      expect(monitoring3).toHaveLength(1);
    });

    test('detail tanpa monitoring tidak masuk ke grup manapun', () => {
      const pohonList = [
        buatPohonDenganMonitoring([
          { id: 'x', monitoring: null }
        ])
      ];

      const { monitoring1, monitoring2, monitoring3 } =
        VerifikasiPohonController
          ._kelompokkanMonitoringPerTahap(pohonList);

      expect(monitoring1).toHaveLength(0);
      expect(monitoring2).toHaveLength(0);
      expect(monitoring3).toHaveLength(0);
    });

    test('beberapa pohon dengan monitoring berbeda', () => {
      const pohonList = [
        buatPohonDenganMonitoring([
          { id: 'a', monitoring: { tahap_monitoring: 1 } }
        ]),
        buatPohonDenganMonitoring([
          { id: 'b', monitoring: { tahap_monitoring: 1 } },
          { id: 'c', monitoring: { tahap_monitoring: 2 } }
        ])
      ];

      const { monitoring1, monitoring2 } =
        VerifikasiPohonController
          ._kelompokkanMonitoringPerTahap(pohonList);

      expect(monitoring1).toHaveLength(2);
      expect(monitoring2).toHaveLength(1);
    });

    test('pohon tanpa detailMonitoring → semua grup kosong', () => {
      const pohonList = [
        { id_pohon: 1, detailMonitoring: [] }
      ];

      const { monitoring1, monitoring2, monitoring3 } =
        VerifikasiPohonController
          ._kelompokkanMonitoringPerTahap(pohonList);

      expect(monitoring1).toHaveLength(0);
      expect(monitoring2).toHaveLength(0);
      expect(monitoring3).toHaveLength(0);
    });

    test('setiap item dalam grup memiliki referensi ke pohon asalnya', () => {
      const pohon = buatPohonDenganMonitoring([
        { id: 'a', monitoring: { tahap_monitoring: 1 } }
      ]);

      const { monitoring1 } =
        VerifikasiPohonController
          ._kelompokkanMonitoringPerTahap([pohon]);

      expect(monitoring1[0].pohon).toBe(pohon);
    });

  });


  // ===========================================================
  // METHOD: approve
  // ===========================================================
  describe('approve', () => {

    test('mengirim pesan error jika selected_pohon kosong', async () => {
      const { req, res } = buatReqRes({
        body: { selected_pohon: null, id_penanaman: '1' }
      });

      await VerifikasiPohonController.approve(req, res);

      expect(res.send).toHaveBeenCalledWith('Pilih minimal 1 pohon');
      expect(Pohon.update).not.toHaveBeenCalled();
    });

    test('mengirim pesan error jika selected_pohon array kosong', async () => {
      const { req, res } = buatReqRes({
        body: { selected_pohon: [], id_penanaman: '1' }
      });

      await VerifikasiPohonController.approve(req, res);

      expect(res.send).toHaveBeenCalledWith('Pilih minimal 1 pohon');
    });

    test('memanggil Pohon.update dengan status disetujui', async () => {
      Pohon.update.mockResolvedValue([1]);

      const { req, res } = buatReqRes({
        body: {
          selected_pohon: ['10', '20'],
          id_penanaman:   '5'
        }
      });

      await VerifikasiPohonController.approve(req, res);

      expect(Pohon.update).toHaveBeenCalledTimes(1);

      const [payload] = Pohon.update.mock.calls[0];
      expect(payload.status_verifikasi).toBe('disetujui');
      expect(payload.catatan_koreksi).toBeNull();
      expect(payload.verified_by_user_id).toBe(99);
    });

    test('melakukan redirect ke halaman detail setelah approve', async () => {
      Pohon.update.mockResolvedValue([1]);

      const { req, res } = buatReqRes({
        body: {
          selected_pohon: '10',
          id_penanaman:   '5'
        }
      });

      await VerifikasiPohonController.approve(req, res);

      expect(res.redirect).toHaveBeenCalledWith(
        '/admin-wilayah/verifikasi-pohon/5'
      );
    });

    test('mengirim error.message jika terjadi exception', async () => {
      Pohon.update.mockRejectedValue(new Error('DB Error'));

      const { req, res } = buatReqRes({
        body: {
          selected_pohon: '10',
          id_penanaman:   '5'
        }
      });

      await VerifikasiPohonController.approve(req, res);

      expect(res.send).toHaveBeenCalledWith('DB Error');
    });

    test('menerima selected_pohon string tunggal (bukan array)', async () => {
      Pohon.update.mockResolvedValue([1]);

      const { req, res } = buatReqRes({
        body: {
          selected_pohon: '42',
          id_penanaman:   '7'
        }
      });

      await VerifikasiPohonController.approve(req, res);

      expect(Pohon.update).toHaveBeenCalledTimes(1);
      expect(res.redirect).toHaveBeenCalled();
    });

  });


  // ===========================================================
  // METHOD: revisi
  // ===========================================================
  describe('revisi', () => {

    test('mengirim pesan error jika selected_pohon kosong', async () => {
      const { req, res } = buatReqRes({
        body: { selected_pohon: null, id_penanaman: '1' }
      });

      await VerifikasiPohonController.revisi(req, res);

      expect(res.send).toHaveBeenCalledWith('Pilih minimal 1 pohon');
      expect(Pohon.update).not.toHaveBeenCalled();
    });

    test('memanggil Pohon.update dengan status revisi dan catatan', async () => {
      Pohon.update.mockResolvedValue([1]);

      const { req, res } = buatReqRes({
        body: {
          selected_pohon:   ['10'],
          catatan_koreksi:  'Foto kurang jelas',
          id_penanaman:     '5'
        }
      });

      await VerifikasiPohonController.revisi(req, res);

      const [payload] = Pohon.update.mock.calls[0];
      expect(payload.status_verifikasi).toBe('revisi');
      expect(payload.catatan_koreksi).toBe('Foto kurang jelas');
      expect(payload.verified_by_user_id).toBe(99);
    });

    test('melakukan redirect setelah revisi berhasil', async () => {
      Pohon.update.mockResolvedValue([1]);

      const { req, res } = buatReqRes({
        body: {
          selected_pohon:  ['10'],
          catatan_koreksi: 'Catatan',
          id_penanaman:    '3'
        }
      });

      await VerifikasiPohonController.revisi(req, res);

      expect(res.redirect).toHaveBeenCalledWith(
        '/admin-wilayah/verifikasi-pohon/3'
      );
    });

    test('mengirim error.message jika terjadi exception', async () => {
      Pohon.update.mockRejectedValue(new Error('Koneksi gagal'));

      const { req, res } = buatReqRes({
        body: {
          selected_pohon:  '10',
          catatan_koreksi: 'Catatan',
          id_penanaman:    '5'
        }
      });

      await VerifikasiPohonController.revisi(req, res);

      expect(res.send).toHaveBeenCalledWith('Koneksi gagal');
    });

  });


  // ===========================================================
  // METHOD: detail
  // ===========================================================
  describe('detail', () => {

    test('mengirim pesan error jika penanaman tidak ditemukan', async () => {
      Penanaman.findByPk.mockResolvedValue(null);

      const { req, res } = buatReqRes({
        params: { id_penanaman: '999' }
      });

      await VerifikasiPohonController.detail(req, res);

      expect(res.send).toHaveBeenCalledWith(
        'Data penanaman tidak ditemukan'
      );
      expect(Pohon.findAll).not.toHaveBeenCalled();
    });

    test('merender view detail dengan data yang benar', async () => {
      const mockPenanaman = { id_penanaman: 1, program: {} };

      const mockPohon = {
        id_pohon:         1,
        detailMonitoring: [
          buatDetail({ monitoring: { tahap_monitoring: 1 } }),
          buatDetail({ monitoring: { tahap_monitoring: 2 } })
        ]
      };

      Penanaman.findByPk.mockResolvedValue(mockPenanaman);
      Pohon.findAll.mockResolvedValue([mockPohon]);

      const { req, res } = buatReqRes({
        params: { id_penanaman: '1' }
      });

      await VerifikasiPohonController.detail(req, res);

      expect(res.render).toHaveBeenCalledWith(
        'admin-wilayah/verifikasi-pohon/detail',
        expect.objectContaining({
          title:      'Detail Verifikasi Pohon',
          penanaman:  mockPenanaman,
          monitoring1: expect.any(Array),
          monitoring2: expect.any(Array),
          monitoring3: expect.any(Array)
        })
      );
    });

    test('mengirim error.message jika terjadi exception', async () => {
      Penanaman.findByPk.mockRejectedValue(
        new Error('DB timeout')
      );

      const { req, res } = buatReqRes({
        params: { id_penanaman: '1' }
      });

      await VerifikasiPohonController.detail(req, res);

      expect(res.send).toHaveBeenCalledWith('DB timeout');
    });

  });

  describe('index', () => {

    test('merender view index dengan data yang benar', async () => {

      const mockPohon = buatPohon({
        status_verifikasi: 'disetujui',
        detailMonitoring:  []
      });

      const mockPenanaman = [
        {
          id_penanaman: 1,
          program: {
            pohon_terkumpul: 5,
            dataValues: { kode_wilayah: '3201' }
          },
          pohon: [mockPohon]
        }
      ];

      Penanaman.findAll.mockResolvedValue(mockPenanaman);
      WilayahService.mapWilayah.mockResolvedValue({
        provinsi: 'Jawa Barat'
      });

      const { req, res } = buatReqRes();

      await VerifikasiPohonController.index(req, res);

      expect(res.render).toHaveBeenCalledWith(
        'admin-wilayah/verifikasi-pohon/index',
        expect.objectContaining({
          title:      'Verifikasi Pohon',
          activePage: 'verifikasi',
          data:       expect.any(Array)
        })
      );
    });

    test('data yang dirender memiliki field yang diharapkan', async () => {

      const mockPohon = buatPohon({
        status_verifikasi: 'disetujui',
        detailMonitoring:  []
      });

      const mockPenanaman = [
        {
          id_penanaman: 42,
          program: {
            pohon_terkumpul: 10,
            dataValues: {}
          },
          pohon: [mockPohon]
        }
      ];

      Penanaman.findAll.mockResolvedValue(mockPenanaman);
      WilayahService.mapWilayah.mockResolvedValue({});

      const { req, res } = buatReqRes();

      await VerifikasiPohonController.index(req, res);

      const { data } = res.render.mock.calls[0][1];
      expect(data[0]).toMatchObject({
        id_penanaman:     42,
        total_pohon:      10,
        total_verifikasi: 1,
        total_menunggu:   0
      });
    });

    test('mengirim error.message jika terjadi exception', async () => {
      Penanaman.findAll.mockRejectedValue(
        new Error('Gagal koneksi DB')
      );

      const { req, res } = buatReqRes();

      await VerifikasiPohonController.index(req, res);

      expect(res.send).toHaveBeenCalledWith('Gagal koneksi DB');
    });

  });

  describe('approveMonitoring', () => {

    test('mengirim error jika selected_monitoring kosong', async () => {
      const { req, res } = buatReqRes({
        body: {
          selected_monitoring: null,
          id_penanaman: '1'
        }
      });

      await VerifikasiPohonController.approveMonitoring(req, res);

      expect(res.send).toHaveBeenCalledWith(
        'Pilih minimal 1 monitoring'
      );
    });

    test('memanggil DetailMonitoring.update dengan status disetujui', async () => {

      DetailMonitoring.update.mockResolvedValue([1]);
      DetailMonitoring.findOne.mockResolvedValue(
        // status bukan mati → tidak ada propagasi
        buatDetail({ status: 'hidup' })
      );

      const { req, res } = buatReqRes({
        body: {
          selected_monitoring: '1|10',
          id_penanaman:        '5'
        }
      });

      await VerifikasiPohonController.approveMonitoring(req, res);

      expect(DetailMonitoring.update).toHaveBeenCalledTimes(1);

      const [payload] = DetailMonitoring.update.mock.calls[0];
      expect(payload.status_verifikasi).toBe('disetujui');
      expect(payload.catatan_koreksi).toBeNull();
    });

    test('melakukan redirect setelah approve monitoring berhasil', async () => {
      DetailMonitoring.update.mockResolvedValue([1]);
      DetailMonitoring.findOne.mockResolvedValue(
        buatDetail({ status: 'hidup' })
      );

      const { req, res } = buatReqRes({
        body: {
          selected_monitoring: '1|10',
          id_penanaman:        '7'
        }
      });

      await VerifikasiPohonController.approveMonitoring(req, res);

      expect(res.redirect).toHaveBeenCalledWith(
        '/admin-wilayah/verifikasi-pohon/7'
      );
    });

    test('propagasi disetujui ke auto-generated jika pohon mati', async () => {

      // Monitoring tahap 1 yang di-approve, status mati
      const detailMati = buatDetail({
        status: 'mati',
        foto_monitoring: '[]'
      });

      // Monitoring auto-generated di tahap 2 (mati + foto kosong)
      const detailAutoTahap2 = buatDetail({
        id_monitoring:   2,
        status:          'mati',
        foto_monitoring: '[]'
      });

      DetailMonitoring.update.mockResolvedValue([1]);

      DetailMonitoring.findOne
        .mockResolvedValueOnce(detailMati)
        .mockResolvedValueOnce(detailAutoTahap2)
        .mockResolvedValueOnce(null); // tahap 3 tidak ada

      Monitoring.findByPk.mockResolvedValue({
        id_monitoring:    1,
        tahap_monitoring: 1
      });

      Monitoring.findOne
        .mockResolvedValueOnce({
          id_monitoring:    2,
          tahap_monitoring: 2
        })
        .mockResolvedValueOnce({
          id_monitoring:    3,
          tahap_monitoring: 3
        });

      const { req, res } = buatReqRes({
        body: {
          selected_monitoring: '1|10',
          id_penanaman:        '5'
        }
      });

      await VerifikasiPohonController.approveMonitoring(req, res);

      // detailAutoTahap2.update harus dipanggil karena auto-generated
      expect(detailAutoTahap2.update).toHaveBeenCalledWith(
        expect.objectContaining({
          status_verifikasi: 'disetujui'
        })
      );
    });

    test('tidak propagasi jika pohon tidak mati', async () => {

      const detailHidup = buatDetail({ status: 'hidup' });

      DetailMonitoring.update.mockResolvedValue([1]);
      DetailMonitoring.findOne.mockResolvedValue(detailHidup);

      const { req, res } = buatReqRes({
        body: {
          selected_monitoring: '1|10',
          id_penanaman:        '5'
        }
      });

      await VerifikasiPohonController.approveMonitoring(req, res);

      // Monitoring.findByPk tidak boleh dipanggil karena bukan mati
      expect(Monitoring.findByPk).not.toHaveBeenCalled();
    });

    test('mengirim error.message jika terjadi exception', async () => {
      DetailMonitoring.update.mockRejectedValue(
        new Error('Update gagal')
      );

      const { req, res } = buatReqRes({
        body: {
          selected_monitoring: '1|10',
          id_penanaman:        '5'
        }
      });

      await VerifikasiPohonController.approveMonitoring(req, res);

      expect(res.send).toHaveBeenCalledWith('Update gagal');
    });

  });


  // ===========================================================
  // METHOD: revisiMonitoring
  // ===========================================================
  describe('revisiMonitoring', () => {

    test('mengirim error jika selected_monitoring kosong', async () => {
      const { req, res } = buatReqRes({
        body: {
          selected_monitoring: [],
          id_penanaman: '1'
        }
      });

      await VerifikasiPohonController.revisiMonitoring(req, res);

      expect(res.send).toHaveBeenCalledWith(
        'Pilih minimal 1 monitoring'
      );
    });

    test('memanggil DetailMonitoring.update dengan status revisi dan catatan', async () => {

      DetailMonitoring.update.mockResolvedValue([1]);
      DetailMonitoring.findOne.mockResolvedValue(
        buatDetail({ status: 'hidup' })
      );

      const { req, res } = buatReqRes({
        body: {
          selected_monitoring: '1|10',
          catatan_koreksi:     'Foto buram',
          id_penanaman:        '5'
        }
      });

      await VerifikasiPohonController.revisiMonitoring(req, res);

      const [payload] = DetailMonitoring.update.mock.calls[0];
      expect(payload.status_verifikasi).toBe('revisi');
      expect(payload.catatan_koreksi).toBe('Foto buram');
    });

    test('propagasi revisi ke auto-generated dengan catatan yang benar', async () => {

      const detailMati = buatDetail({
        status:          'mati',
        foto_monitoring: '[]'
      });

      const detailAutoTahap2 = buatDetail({
        id_monitoring:   2,
        status:          'mati',
        foto_monitoring: '[]'
      });

      DetailMonitoring.update.mockResolvedValue([1]);

      DetailMonitoring.findOne
        .mockResolvedValueOnce(detailMati)
        .mockResolvedValueOnce(detailAutoTahap2)
        .mockResolvedValueOnce(null);

      Monitoring.findByPk.mockResolvedValue({
        id_monitoring:    1,
        tahap_monitoring: 1
      });

      Monitoring.findOne
        .mockResolvedValueOnce({
          id_monitoring:    2,
          tahap_monitoring: 2
        })
        .mockResolvedValueOnce({
          id_monitoring:    3,
          tahap_monitoring: 3
        });

      const { req, res } = buatReqRes({
        body: {
          selected_monitoring: '1|10',
          catatan_koreksi:     'Catatan utama',
          id_penanaman:        '5'
        }
      });

      await VerifikasiPohonController.revisiMonitoring(req, res);

      // Catatan propagasi harus menyebut tahap asal
      expect(detailAutoTahap2.update).toHaveBeenCalledWith(
        expect.objectContaining({
          status_verifikasi: 'revisi',
          catatan_koreksi:   'Mengikuti revisi monitoring ke-1'
        })
      );
    });

    test('melakukan redirect setelah revisi monitoring berhasil', async () => {
      DetailMonitoring.update.mockResolvedValue([1]);
      DetailMonitoring.findOne.mockResolvedValue(
        buatDetail({ status: 'hidup' })
      );

      const { req, res } = buatReqRes({
        body: {
          selected_monitoring: '1|10',
          catatan_koreksi:     'Catatan',
          id_penanaman:        '8'
        }
      });

      await VerifikasiPohonController.revisiMonitoring(req, res);

      expect(res.redirect).toHaveBeenCalledWith(
        '/admin-wilayah/verifikasi-pohon/8'
      );
    });

    test('mengirim error.message jika terjadi exception', async () => {
      DetailMonitoring.update.mockRejectedValue(
        new Error('Timeout')
      );

      const { req, res } = buatReqRes({
        body: {
          selected_monitoring: '1|10',
          catatan_koreksi:     'Catatan',
          id_penanaman:        '5'
        }
      });

      await VerifikasiPohonController.revisiMonitoring(req, res);

      expect(res.send).toHaveBeenCalledWith('Timeout');
    });

  });

});